theZiz/aha

Makefile

Instead of hardcoding `gcc`, use the `$(CC)` variable to allow other
compilers (e.g., `clang`, `gcc-4.9`, etc.).

Generalize compiler.

---

Makefile

Replace GNU make syntax with POSIX standard equivalent. This allows the
software to be built with other versions of 'make' (e.g., on BSD).

POSIX-ify Makefile.

---

Makefile

Allow to overwrite `MANDIR`, it's OS specific and configurable in pkgsrc. It's usually `share/man` (GNU) or `man` (BSD).
Files must be installed with specific file mode. Previously man-page was installed with executable bit.
`BIN:=` and `MAN:=` didn't work well with overwrittable `MANDIR`, go for canonical way of using these paths.

NetBSD: Sanity installation of files and directories

---

aha.1

In the roff language, the escaped double quote (`\"`) introduces a comment;
use plain double quote (`"`) instead.

Fix description of the --title option in the manual page

---

Makefile

Using `MANDIR` as it is described by the [GNU Coding Standards], to increase interoperability with package managers and operating systems. Previously, `MANDIR` was a variable that described a path relative to `PREFIX`; however, it should be an **absolute** path.
Related discussions:
* https://github.com/Homebrew/homebrew-core/pull/11208
* https://github.com/theZiz/aha/pull/15
[GNU Coding Standards]: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

fix MANDIR variable

---

Makefile
README.md

Following our discussion from #27: `MANDIR` is now defined in terms of `DATAROOTDIR` as specified by the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html). This also means that `MANDIR` now points to `/usr/local/share/man`, breaking compatibility with previous versions of aha.
Let me know what you think!

Use datarootdir in compliance with GNU coding standards.

---

aha.c

This changeset makes the program escape HTML special characters (`<&">`) when printing the document `<title>`. Previously it was possible to break the document subtly by doing e.g. `aha --title 'ha</title>HA HA'`.

Escape HTML special characters in title

---

aha.c

This changeset makes the program return a non-zero exit code when encountering unknown options. This makes it easier to detect when the program failed to convert its input to HTML (e.g. in shell scripts).

Return non-zero on unknown options

---

aha.c

This changeset adds a `enum ColorScheme` to the code to replace the magic numbers used for representing the colour scheme. I believe this will make the code a bit more readable.

Use an enum for color scheme

---

aha.c

This changeset makes the program print error names when failing to open a file that was provided using the `-p` option, or when reading the next byte in `getNextChar()` fails.

Print IO error names

---

aha.c

Even when using the `--iso` option, the `<meta>` tag in the header still says `charset=UTF-8`. This changeset makes the XML `encoding` and `http-equiv="Content-Type"` values consistent.

Fix HTTP-equiv charset

---

Makefile
aha.c

This changeset adds warnings to `CFLAGS` and fixes two places which emitted warnings: unsigned-vs-signed-int comparison and an unused variable.

Enable warnings

---

aha.c

This changeset adds two arrays, `fcstyle` and `bcstyle`, holding information about foreground and background colours. This allows us to remove the colouring `switch` statement and replace it with a simple `printf(array[index])`.

Use an array instead of switch for printing colors

---

aha.c

This changeset adds a `value` field to `struct selem`. I believe this change makes the code more readable in regards to handling the SGR sequences.

Add value field to parse-elem

---

aha.c

This changeset adds support for the "crossed-out" attribute (SGR 9 and 29).

Add support for crossed-out characters (SGR 9)

---

aha.c

This changeset puts the output state (colours, bold, underline, blink) into a struct. This allows to remove state change checks with calls to a new function, `statesDiffer`, making "forgot to change code in one place" errors less likely.

Put application state into struct

---

aha.c

Currently, SGR27 ("reverse off") will always swap background and foreground colours, even if we're not in inverse mode – e.g. an input like `^[SGR27;aaa^[SGR27;bbb^[SGR27;ccc^[SGR27;ddd` will produce output with alternating colours, even though it all should use the default colours.
This changeset fixes said bug. It also moves colour inverting code to a function to reduce the amount of copy-paste present in the code.

SGR27 ("reverse off") should not invert colours unless already in inverse mode

---

aha.c

The `make_rgb()` function generated a string in the `r,g,b` format. Since the individual bytes are 8-bit, the longest possible generated string is `XXX,YYY,ZZZ` - which is 11 bytes _without_ the NUL-terminator. To store a proper, NUL-terminated string, we need 12 bytes.
The RGB buffer size was set to 11, which meant that in the longest-case, the code wrote one byte past the buffer. This could lead to a segfault.

Fix RGB buffer size (from 11 bytes to 12)

---

aha.c

This PR fixes a bug where the wrong CSS property was used for making the text _italic_.

Fix italics CSS (is "font-weight", should be "font-style")

---

aha.c

Hey, aha is pretty cool! I'm using it in conjuction with wkhtmltoimage to capture clean ‘screenshots’ of terminal output.
One issue I've noticed is that the images thus produced often have an extra blank line at the end, which I think is due to this `\n` inserted with the span close tag when there's some ANSI formatting still in effect at the last character—this PR takes it out.

Remove extra linebreak at end

---

aha.c

This changeset makes the program use the #hex format when outputting 8-bit/24-bit mode colours. This will slightly reduce the output size.

Use #hex format for colours

---

aha.c

An HTML5 header would be far more preferable than an XHTML header.

Use doctype HTML5 instead of XHTML

---

Makefile

This compiler does not use -std=c99 flag.

Added vbcc support.

---

aha.c

This closes #72
Signed-off-by: Ted Lyngmo <ted@lyncon.se>

Add --style option

---

Makefile

This changeset makes the Makefile use the `INSTALL` variable during "make install".
The default value is set to `install -p` so that file timestamps are preserved.

Preserve timestamps in "make install"

---

aha.c

Some of the program options take arguments that are then printed inside the document, such as `--title` or `--style`. Some of those were printed as-is, without properly escaping HTML entities. This changeset replaces "raw" prints with safe ones.

Escape HTML where needed

---

aha.c

Make fails with error: #pragma GCC diagnostic not allowed inside functions
GCC versions < 5 do not allow #pragma GCC diagnostic inside functions.
Added wrapper around #pragma GCC blocks to check GNUC version and only use if >= version 5.

Fix to allow compiling with older GCC variants

---

README.md

This package is exactly what I was looking for.  Thanks for creating it.  I found it via conda, so was suprised to see it was not mentioned as an install option (nor homebrew- i tested brew aha on Catalina, it worked, and I tested conda aha on Ubuntu 18 and 20 and it worked).  These routes will certainly make the tool more approachable.  Thanks again--

Adding brief details on 2 other ways to install
